import { defineConfig } from 'orval';

export default defineConfig({
  'dol-api': {
    input: {
      target: './openapi-v4.yaml',
      validation: false,
    },
    output: {
      mode: 'split',
      target: './src/api/generated/endpoints.ts',
      client: 'axios',
      override: {
        mutator: {
          path: './src/api/client.ts',
          name: 'customInstance',
        },
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * Department of Labor API',
          ' * OpenAPI spec version: 4.0.0',
          ' */',
          '',
        ],
      },
    },
  },
  'dol-mcp': {
    input: {
      target: './openapi-v4.yaml',
      validation: false,
    },
    output: {
      mode: 'split',
      target: './src/mcp/http-client.ts',
      client: 'fetch',
      schemas: './src/mcp/http-schemas',
      override: {
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * Department of Labor API',
          ' * OpenAPI spec version: 4.0.0',
          ' */',
          '',
        ],
        useNativeEnums: true,
      },
    },
    hooks: {
      afterAllFilesWrite: 'bun run scripts/fix-mcp-types.ts',
    },
  },
});
