import { defineConfig } from 'orval';

export default defineConfig({
  // SDK configuration
  'dol-api': {
    input: {
      target: './openapi-v4.yaml',
      validation: false,
    },
    output: {
      mode: 'split',
      target: './src/api/generated/endpoints.ts',
      client: 'axios-functions',
      override: {
        mutator: {
          path: './src/api/client.ts',
          name: 'customInstance',
        },
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * Department of Labor API',
          ' * OpenAPI spec version: 4.0.0',
          ' */',
          '',
        ],
      },
    },
  },
  // Documentation configuration
  'docs': {
    input: './openapi-v4.yaml',
    output: {
      target: 'src/api/endpoints/docs.ts',
      docs: {
        out: './docs/typedoc',
        disableSources: true,
        plugin: ['typedoc-plugin-markdown'],
      },
    },
  },
  // MCP server configuration
  'dol-mcp': {
    input: {
      target: './openapi-v4.yaml',
      validation: false,
    },
    output: {
      mode: 'single',
      target: './src/mcp/handlers.ts',
      client: 'mcp',
      baseUrl: 'https://api.dol.gov',
      schemas: './src/mcp/http-schemas',
      override: {
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * Department of Labor API',
          ' * OpenAPI spec version: 4.0.0',
          ' */',
          '',
        ],
        useNativeEnums: true,
      },
    },
  },
});
