import { defineConfig } from 'orval';

export default defineConfig({
  // SDK configuration
  ecfr: {
    input: {
      target: './docs/v1-openapi3.json',
    },
    output: {
      mode: 'split',
      target: './src/api/generated/endpoints.ts',
      schemas: './src/api/generated/models',
      baseUrl: 'https://www.ecfr.gov',
      client: 'axios',
      prettier: false,
      override: {
        mutator: {
          path: './src/api/client.ts',
          name: 'customInstance',
        },
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * eCFR API Documentation',
          ' * OpenAPI spec version: 2.0',
          ' */',
          '',
        ],
      },
    },
  },
  // MCP server configuration
  'ecfr-mcp': {
    input: {
      target: './docs/v1-openapi3.json',
    },
    output: {
      mode: 'single',
      client: 'mcp',
      baseUrl: 'https://www.ecfr.gov',
      target: './src/mcp/handlers.ts',
      schemas: './src/mcp/http-schemas',
      override: {
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * eCFR API Documentation',
          ' * OpenAPI spec version: 2.0',
          ' */',
          '',
        ],
      },
    },
  },
});
