/* /* eslint-disable *\/ */
/**
 * /* tslint:disable *\/
 * // @ts-nocheck
 * /**
 *  * Generated by orval 🍺
 *  * Do not edit manually.
 *  * Department of Labor API
 *  * OpenAPI spec version: 4.0.0
 *  *\/
 * 
 */

import {
  McpServer
} from '@modelcontextprotocol/sdk/server/mcp.js';
  
import {
  StdioServerTransport
} from '@modelcontextprotocol/sdk/server/stdio.js';  

import {
  getDatasetsHandler,
  getAgencyEndpointDataJsonHandler,
  getAgencyEndpointDataXmlHandler,
  getAgencyEndpointDataCsvHandler,
  getAgencyEndpointMetadataJsonHandler,
  getAgencyEndpointMetadataCsvHandler
} from './handlers';
import {
  getDatasetsQueryParams,
  getAgencyEndpointDataJsonParams,
  getAgencyEndpointDataJsonQueryParams,
  getAgencyEndpointDataXmlParams,
  getAgencyEndpointDataXmlQueryParams,
  getAgencyEndpointDataCsvParams,
  getAgencyEndpointDataCsvQueryParams,
  getAgencyEndpointMetadataJsonParams,
  getAgencyEndpointMetadataCsvParams
} from './tool-schemas.zod';

const server = new McpServer({
  name: 'departmentOfLaborDOLOpenDataAPIServer',
  version: '1.0.0',
});


server.tool(
  'getDatasets',
  'List Available Datasets',
  {
    queryParams: getDatasetsQueryParams
  },
  getDatasetsHandler
);

server.tool(
  'getAgencyEndpointDataJson',
  'Retrieve Dataset Data',
  {
    pathParams: getAgencyEndpointDataJsonParams,
    queryParams: getAgencyEndpointDataJsonQueryParams
  },
  getAgencyEndpointDataJsonHandler
);

server.tool(
  'getAgencyEndpointDataXml',
  'Retrieve Dataset Data',
  {
    pathParams: getAgencyEndpointDataXmlParams,
    queryParams: getAgencyEndpointDataXmlQueryParams
  },
  getAgencyEndpointDataXmlHandler
);

server.tool(
  'getAgencyEndpointDataCsv',
  'Retrieve Dataset Data',
  {
    pathParams: getAgencyEndpointDataCsvParams,
    queryParams: getAgencyEndpointDataCsvQueryParams
  },
  getAgencyEndpointDataCsvHandler
);

server.tool(
  'getAgencyEndpointMetadataJson',
  'Retrieve Dataset Metadata',
  {
    pathParams: getAgencyEndpointMetadataJsonParams
  },
  getAgencyEndpointMetadataJsonHandler
);

server.tool(
  'getAgencyEndpointMetadataCsv',
  'Retrieve Dataset Metadata',
  {
    pathParams: getAgencyEndpointMetadataCsvParams
  },
  getAgencyEndpointMetadataCsvHandler
);

const transport = new StdioServerTransport();

server.connect(transport).then(() => {
  console.error('MCP server running on stdio');
}).catch(console.error);
