import { defineConfig } from 'orval';

export default defineConfig({
  // SDK configuration
  'govinfo-api': {
    input: './openapi.json',
    output: {
      mode: 'split',
      target: './src/api/generated/endpoints.ts',
      schemas: './src/api/generated/model',
      client: 'axios-functions',
      httpClient: 'axios',
      mock: false,
      clean: true,
      prettier: false,
      override: {
        operations: {
          Document: {
            mutator: {
              path: './src/api/client.ts',
              name: 'customInstance',
            },
          },
        },
        mutator: {
          path: './src/api/client.ts',
          name: 'customInstance',
        },
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * GovInfo API Documentation',
          ' * OpenAPI spec version: 3.0.0',
          ' */',
          '',
        ],
      },
    },
  },
  // MCP server configuration
  'govinfo-mcp': {
    input: './openapi.json',
    output: {
      mode: 'single',
      client: 'mcp',
      baseUrl: 'https://api.govinfo.gov',
      target: './src/mcp/handlers.ts',
      schemas: './src/mcp/http-schemas',
      override: {
        header: () => [
          '/* eslint-disable */',
          '/* tslint:disable */',
          '// @ts-nocheck',
          '/**',
          ' * Generated by orval 🍺',
          ' * Do not edit manually.',
          ' * GovInfo API Documentation',
          ' * OpenAPI spec version: 3.0.0',
          ' */',
          '',
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: 'bun run scripts/fix-mcp-types.ts',
    },
  },
});
