import { defineConfig } from "orval";

export default defineConfig({
  "courtlistener-api": {
    input: "./courtlistener-openapi.json",
    output: {
      mode: "split",
      target: "./src/api/generated/endpoints.ts",
      schemas: "./src/api/generated/model",
      client: "axios",
      httpClient: "axios",
      mock: false,
      clean: true,
      prettier: false,
      override: {
        mutator: {
          path: "./src/api/client.ts",
          name: "customInstance",
        },
        header: () => [
          "/* eslint-disable */",
          "/* tslint:disable */",
          "// @ts-nocheck",
          "/**",
          " * Generated by orval 🍺",
          " * Do not edit manually.",
          " * CourtListener API Documentation",
          " * OpenAPI spec version: 3.0.3",
          " */",
          "",
        ],
      },
    },
  },
  "courtlistener-mcp": {
    input: "./courtlistener-openapi.json",
    output: {
      mode: "single",
      client: "mcp",
      baseUrl: "https://www.courtlistener.com",
      target: "./src/mcp/handlers.ts",
      schemas: "./src/mcp/http-schemas",
      override: {
        header: () => [
          "/* eslint-disable */",
          "/* tslint:disable */",
          "// @ts-nocheck",
          "/**",
          " * Generated by orval 🍺",
          " * Do not edit manually.",
          " * CourtListener API Documentation",
          " * OpenAPI spec version: 3.0.3",
          " */",
          "",
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: "bun run scripts/fix-mcp-types.ts",
    },
  },
});
