name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: bun install

      - name: Generate SDKs
        run: bunx turbo generate

      - name: Run format check
        run: bunx turbo format

      - name: Run lint check
        run: bunx turbo check:ci

      - name: Build SDKs
        run: bunx turbo build

      - name: Run tests
        run: bunx turbo test
        env:
          GOV_INFO_API_KEY: ${{ secrets.GOV_INFO_API_KEY }}

      - name: Run integration tests
        run: bunx turbo test:integration
        env:
          GOV_INFO_API_KEY: ${{ secrets.GOV_INFO_API_KEY }}

      - name: Run e2e tests
        run: bunx turbo test:e2e
        env:
          GOV_INFO_API_KEY: ${{ secrets.GOV_INFO_API_KEY }}

      - name: Verify MCP servers
        run: |
          cd packages/ecfr-sdk && bun run scripts/test-mcp-server.ts
          cd packages/federal-register-sdk && echo "Federal Register MCP server test - TODO"
          cd packages/courtlistener-sdk && echo "CourtListener MCP server test - TODO"